sudo: required

services: docker

before_install:
  - docker-compose exec --env 'RAILS_ENV=test' wed rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' wed rails db:migrate 
  - docker-compose exec --env 'RAILS_ENV=test' wed rails test 